language: python
python:
    - "2.7"

install:
    - pip install nose
    - pip install coveralls
    - pip install requests

script:
    - nosetests

after_success:
    coveralls

env:
    global:
        - blueprintID=ae6e0a79-dd62-4d07-b846-6e0a7f00fd5f
        - webServerName=HP Serv1